autosell:
  enabled-by-default: true
  interval-seconds: 180
  autosmelt: true

sellable-items:
  DIAMOND_BLOCK: 5000
  EMERALD_BLOCK: 7500
  GOLD_BLOCK: 2500
  IRON_BLOCK: 1500
  COAL_BLOCK: 1000
  STONE: 25
  COBBLESTONE: 20
  NETHERRACK: 10

smelt-map:
  # --- Overworld Ores ---
  COAL_ORE: COAL
  DEEPSLATE_COAL_ORE: COAL
  IRON_ORE: IRON_INGOT
  DEEPSLATE_IRON_ORE: IRON_INGOT
  GOLD_ORE: GOLD_INGOT
  DEEPSLATE_GOLD_ORE: GOLD_INGOT
  COPPER_ORE: COPPER_INGOT
  DEEPSLATE_COPPER_ORE: COPPER_INGOT
  LAPIS_ORE: LAPIS_LAZULI
  DEEPSLATE_LAPIS_ORE: LAPIS_LAZULI
  REDSTONE_ORE: REDSTONE
  DEEPSLATE_REDSTONE_ORE: REDSTONE
  DIAMOND_ORE: DIAMOND
  DEEPSLATE_DIAMOND_ORE: DIAMOND
  EMERALD_ORE: EMERALD
  DEEPSLATE_EMERALD_ORE: EMERALD

  # --- Nether Ores ---
  NETHER_QUARTZ_ORE: QUARTZ
  NETHER_GOLD_ORE: GOLD_NUGGET
  ANCIENT_DEBRIS: NETHERITE_SCRAP

  # --- End Ores (custom or modded compatibility) ---
  END_ORE: END_STONE # Placeholder – replace if using modded ores

  # --- Misc Blocks That Can Smelt ---
  RAW_IRON_BLOCK: IRON_BLOCK
  RAW_GOLD_BLOCK: GOLD_BLOCK
  RAW_COPPER_BLOCK: COPPER_BLOCK
  SAND: GLASS
  CLAY: BRICK
  WET_SPONGE: SPONGE
