sellable-items:
  # --- Smelted Ores & Raw Drops ---
  IRON_INGOT: 150
  GOLD_INGOT: 250
  COPPER_INGOT: 50
  COAL: 25
  REDSTONE: 20
  LAPIS_LAZULI: 25
  DIAMOND: 500
  EMERALD: 750
  QUARTZ: 100
  GOLD_NUGGET: 10
  NETHERITE_SCRAP: 1000

  # --- Block Forms ---
  DIAMOND_BLOCK: 5000
  EMERALD_BLOCK: 7500
  GOLD_BLOCK: 2500
  IRON_BLOCK: 1500
  COAL_BLOCK: 1000
  COPPER_BLOCK: 500
  NETHERITE_BLOCK: 9000

  # --- Miscellaneous ---
  STONE: 25
  COBBLESTONE: 20
  NETHERRACK: 10
  GLASS: 15
  BRICK: 10
  SPONGE: 100
