name: AscendiaPrisonCore
version: '1.0-SNAPSHOT'
main: me.brynner.ascendiaPrisonCore.AscendiaPrisonCore
api-version: '1.21'
author: Brynner
description: A high-performance, modular Prison Core plugin for the Ascendia Network.
depend: [Vault, PlaceholderAPI]